version: '3'
services:
  workspace:
    build: .
    command: yarn run serve
    depends_on:
        - db
    volumes:
      - .:/home/node/app
    ports:
      - 5000:5000
  db:
    image: mysql:8.0
    # volumes:
    #   - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=api
      - MYSQL_USER=jehu
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - 3306:3306
